import axios from 'axios';

const api = axios.create({
  baseURL: 'http://localhost:8000',
});

/**
 * Uploads an image file to the backend
 * @param {File} file - The image file object from input/dropzone
 * @returns {Promise<string>} - Returns the unique_filename generated by backend
 */
export const uploadImage = async (file) => {
  const formData = new FormData();
  formData.append('file', file);
  
  const response = await api.post('/upload', formData, {
    headers: {
      'Content-Type': 'multipart/form-data',
    },
  });
  return response.data.unique_filename;
};

/**
 * Triggers classical image processing analysis (SIFT, ORB, AKAZE, BRISK)
 * @param {string} filename - The unique_filename of the uploaded image
 * @returns {Promise<Object>} - Returns keypoints, matches, and base64 result images
 */
export const analyzeClassical = async (filename) => {
  const response = await api.post(`/analyze/${filename}`);
  return response.data;
};

/**
 * Triggers AI deep learning model inference (ResNet18 and CNN-LSTM Hybrid)
 * @param {string} filename - The unique_filename of the uploaded image
 * @returns {Promise<Object>} - Returns predictions and confidence metrics
 */
export const analyzeAI = async (filename) => {
  const response = await api.post(`/ai-analyze/${filename}`);
  return response.data;
};

export default api;